### ISSUE TITLE
Freeze schema

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#165]
Procedure to freeze the dbiait_analysis schema into the dbiait_freeze schema.
We need the following procedures:
- [x] freeze a table by name, year, note
- [x] freeze a whole schema by year, note
- [x] clean a set of tables in a specific year (of the dbiait_freeze schema)
- [ ] from the web app (UI) it is neccesary to allow users to select an year (a menu with year from 2000 to 2100 could be enough. Default current year) and put an additional note. Then schedule a freeze task on dramatiq.
