### ISSUE TITLE
DBIAIT: Configuration Tuning

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/C179-DBIAIT#311]
Some last time requests for the operations team concerning DBIAIT:
- [ ] Test LDAPS instead of plain LDAP - Should be already supported. Just test
- [ ] Test muliple LDAP endpoints instead of a single endpoint in the application - Requires some development
- [ ] Install pg_stat_statements in postgresql to debug a PG functions that get stuck
- [ ] Add proxy for statics - This is required to disable DEBUG in UWSGI
- [x] Update FTP mount point in the application to ` /apps/ftp`

**Comment by chpicone** [comment]
@randomorder cause the update of the FTP mount point the application does not work anymore.
I think it is the most urgent task (but simple to do).

**Comment by lpasquali** [comment]
@randomorder @EddyCatt there is a slight problem for ldaps, within the course of the latest operations carried two weeks ago, I tried if ldaps was supported in dbi-ait instances but it is not, the ldaps connectivity is tested and fine.

**Comment by randomorder** [comment]
duplicate of [#106](https://github.com/geosolutions-it/PUBLIACQUA-C179/issues/106#issuecomment-1048543639)
