### ISSUE TITLE
Prepare Jenkins JOBs

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#59]
We need to prepare the following Jenkins JOBs:

- [x] align database schema (install.sql) from scripts in the github repo
- [x] align database procedure (functions.sql) from scripts in the github repo
- [x] align django webapp from the source in the github repo

Each job need to allow the jenkins admin user to decide the destination environment (QA or PROD).

Document the jobs, what they do and how to use them

**Comment by randomorder** [comment]
can we have a 15m chat about this w/ @lpasquali, @chpicone ?

**Comment by chpicone** [comment]
@lpasquali I split the JOB to align database in 2:
- one for the installation
- one for the functions
I think to prepare 1 and copy the job and replace the name of the file to execute.

**Comment by lpasquali** [comment]
> @lpasquali I split the DB JOB to align database in 2:
> 
> * one for the installation
> * one for the functions
> 
> I think you have to prepare just 1 and then copy this job and replace the name of the file to execute.

I would think about one job with two dependent steps (create schemas/tables -> then functions), is there a case where only functions or db have to be applied? @chpicone

**Comment by chpicone** [comment]
Yes, mainly if we need to fix some PlPgSQL functions.

**Comment by lpasquali** [comment]
had some slight problem to adapt the jenkis agent as it is different from how we run it anywhere (in tomcat), but now it's ok (I will need to document how the agents for jeniks are installed on these machines, ansible jenkins will be needed to be transformed in a role for ubuntu and suse @randomorder )

**Comment by randomorder** [comment]
let's ignore the role and just document what you've done please

**Comment by lpasquali** [comment]
jenkins agents are working, jenkins jobs should work as well

**Comment by chpicone** [comment]
@lpasquali thx.
I will leave this issue in test for other days (we are going to test them in Test Environment).
